### ISSUE TITLE
Training with knowledge distillation

### ISSUE THREAD

**Issue by NoVarlok** [jiawangbai/HAT#2]
Hi. First of all, thank you for the excellent article and its implementation.
Your article describes experiments with knowledge distillation from CNN and repository contains a script for training in KD, but it looks incomplete because it uses DistillationLoss, which is not declared either in the repository or in third-party libraries. Could you, please, publish the code of this function to reproduce the results?

**Comment by jiawangbai** [comment]
Sorry to my late reply. I have uploaded the missing loss_adv.py.
